---
title: Victoria Wolfe
timezone: America/New York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
  sass_dir: _sass
