backend:
  name: github
  repo: minicreative/victoriawolfe
  branch: main
  base_url: https://github-auth.tomasroy.com/
editor:
  preview: false
media_folder: "/uploads"
public_folder: "/uploads"
collections:
  - name: "page"
    label: "Pages"
    create: false
    sortable_fields: ['title', 'order']
    files: 
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: body, widget: markdown}


          
    
